#!/usr/bin/env bash

file="/usr/local/bin/kompose"
curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-linux-amd64 -o $file 
chmod +x $file 
#snap installl kompose  # has issues

