#!/usr/bin/env bash
set -ex
sleeptime=10

install_docker_ce(){
  sudo apt-get remove docker docker-engine docker.io containerd runc | true
  sudo apt-get update
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
  sudo apt-get update
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io
}


install_docker(){
  snap install docker
}


test_docker(){
  sleep $sleeptime
  sudo docker run hello-world
  systemctl status snap.docker.dockerd.service
}


test_docker_ce(){
  sleep $sleeptime
  sudo systemctl is-active docker
  sudo systemctl is-enabled docker
  sudo docker run hello-world
}


install_docker
test_docker
