apiVersion: v1
kind: Pod
metadata:
  name: demo-nfs-mount 
spec:
  containers:
  - name: demo-nfs-mount 
    image: jeremybusk/coredns-rdns:latest
    volumeMounts:
    - mountPath: /conf
      name: demo-nfs-mount 
  volumes:
  - name:  demo-nfs-mount 
    nfs:
      server: 10.64.10.23 
      path: /nas/demo-coredns-rdns/conf
