#!/usr/bin/env bash
set -e
shopt -s expand_aliases
alias kubectl='microk8s kubectl'
kubectl delete -f mysql-deployment.yml 
kubectl delete -f mysql-pv.yml

# psql -h localhost -U postgresadmin1 --password -p 31070 postgresdb
