apiVersion: v1
kind: Service
metadata:
  name: demo-coredns-rdns-nfs 
  labels:
    app: demo-coredns-rdns-nfs
spec:
  ports:
  - port: 53
    protocol: TCP
    name: dns-tcp
  - port: 53 
    protocol: UDP 
    name: dns-udp
  type: NodePort
  selector:
    app: demo-coredns-rdns-nfs 
